### ISSUE TITLE
Support for Image Field Caption module

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/flexslider#11]
I found the [Image Field Caption](https://github.com/backdrop-contrib/image_field_caption) in github and then found a this patch on Drupal.org.  https://www.drupal.org/project/flexslider/issues/2384525

I did that and it works great.

**Comment by jenlampton** [comment]
I'm not sure if flexslider should include code for image_field_caption, or if image_field_caption should include support for flexslider.

**Comment by sdubois** [comment]
I can confirm the changes mentioned in the drupal.org issue by @keiserjb are working for me as well. It would be great to roll them into a release of this module for Backdrop I think.

**Comment by sdubois** [comment]
Created a PR for this https://github.com/backdrop-contrib/flexslider/pull/21

**Comment by jenlampton** [comment]
Fixed by https://github.com/backdrop-contrib/flexslider/pull/21
