### ISSUE TITLE
Github project "About" still lists Drupal

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/flexslider#13]
> ![flexslider-about](https://user-images.githubusercontent.com/871421/116395552-e2401080-a7e9-11eb-815b-a97076b3cdc6.png)

**Comment by jenlampton** [comment]
Updated :)
<img width="308" alt="Screen Shot 2022-08-17 at 11 19 40 PM" src="https://user-images.githubusercontent.com/397895/185308143-262cbfab-2610-4fa8-8dde-404f06c7c914.png">
