### ISSUE TITLE
Optionset 'clone' link not working

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/flexslider#2]
I tried to clone a FlexSlider Optionset and got only a nearly blank page. To reproduce the problem:
- Go to _admin/config/media/flexslider_.
- In the Optionset List, under "Operations", use the "Clone" link of the dropdown menu.
- You get a nearly empty page (_admin/config/media/flexslider/clone/default_) with page title "Clone optionset", but without form.

More information:
- Backdrop 1.4.2, FlexSlider 1.x-2.0.0, no other contrib nor any custom modules
- On _admin/reports/dblog_, I get no log messages related to FlexSlider.
- Inspecting the mentioned "Clone optionset" page with Firebug, I saw that there is a (probably incomplete) clone form with some hidden elements, cf. the following HTML:

```
<form accept-charset="UTF-8" id="flexslider-clone-form" method="post" action="/admin/config/media/flexslider/clone/default">
  <div>
    <input type="hidden" value="form-..." name="form_build_id">
    <input type="hidden" value="..." name="form_token">
    <input type="hidden" value="flexslider_clone_form" name="form_id">
  </div>
</form>
```

**Comment by olafgrabienski** [comment]
Additional information: while it's not possible to clone an Optionset, the "Add Optionset" link works fine. Adding an Optionset this way, you clone the default set, which might be a workaround for the moment.

**Comment by jenlampton** [comment]
Thanks for the bug report @olafgrabienski!  I have gone ahead and removed the "clone" button for now (since I am making a new release and wanted the bug not to be in it) BUT I would like to have that feature back! 

Here is the issue to put it back  :) https://github.com/backdrop-contrib/flexslider/issues/5
